version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "mcabreradev"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    ignore:
      # Allow critical security updates but ignore other major updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        # Exception: Allow major updates for security-critical packages
      - dependency-name: "semver"
        update-types: ["version-update:semver-major"]
      - dependency-name: "minimatch"
        update-types: ["version-update:semver-major"]

  # Filter package
  - package-ecosystem: "npm"
    directory: "/packages/filter"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "mcabreradev"
    commit-message:
      prefix: "chore(filter)"
      include: "scope"
    labels:
      - "dependencies"
      - "filter"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "mcabreradev"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "ci"
    ignore:
      # Pin critical actions to specific versions
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-major"]
      - dependency-name: "actions/setup-node"
        update-types: ["version-update:semver-major"]
